gestion_parc/urls.py
from django.urls import path


urlpatterns = [
    
]
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    # Liste des employés
    path('employes/', views.liste_employes, name='liste_employes'),
    
    # Détail d'un employé
    path('employe/<int:id>/', views.detail_employe, name='detail_employe'),
    path('employe/<int:id>/edite', views.modifier_employe, name='modifier_employe'),
    path('employe/<int:id>/supprimer', views.supprimer_employe, name='supprimer_employe'),
    
    # Liste des services
    path('services/', views.liste_services, name='liste_services'),
    path('services/<int:id>/', views.detail_service, name='detail_service'),
    path('services/<int:id>/edite', views.modifier_service, name='modifier_service'),
    path('services/<int:id>/supprimer', views.supprimer_service, name='supprimer_service'),
    
    
    # Liste des Antennes
    path('antennes/', views.liste_antennes, name='liste_antennes'),
    path('antennes/<int:id>/', views.detail_antenne, name='detail_antenne'),
    path('antennes/<int:id>/edite', views.modifier_antenne, name='modifier_antenne'),
    path('antennes/<int:id>/supprimer', views.supprimer_antenne, name='supprimer_antenne'),
    
    
    
    # Les équipements
    path('equipements/', views.liste_equipements, name='liste_equipements'),
    
    path('equipement/<int:id>/', views.detail_equipement, name='detail_equipement'),
    path('equipement/<int:id>/edite', views.modifier_equipement, name='modifier_equipement'),
    path('equipements/<int:id>/supprimer', views.supprimer_equipement, name='supprimer_equipement'),

    
    # # Historique des actions sur un équipement
    # path('historique/equipement/<int:equipement_id>/', views.historique_equipement, name='historique_equipement'),
    
    # Ajouter un nouvel employé
    path('employe/ajouter/', views.ajouter_employe, name='ajouter_employe'),
    
    # Ajouter un nouvel Service
    path('service/ajouter/', views.ajouter_service, name='ajouter_service'),
    
    # Ajouter un nouvel équipement
    path('equipement/ajouter/', views.ajouter_equipement, name='ajouter_equipement'),
    

    path('service/ajouter/', views.ajouter_service, name='ajouter_service'),
    
    # authentification route
    
    path('inscription/', views.inscription, name='inscription'),
    path('connexion/', views.connexion, name='connexion'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    
    # historique
    
    path('historique/', views.historique_list, name='historique_list'),
    path('historique/ajouter', views.ajouter_historique, name='ajouter_historique'),
    
    path('gestion_parc/setting', views.settings, name='settings'),
]

parc_info/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('gestion_parc.urls')),
]

gestion_parc/models.py
from django.db import models
from django.contrib.auth.models import User






class Antenne(models.Model):
    nom = models.CharField(max_length=100, unique=True)
    ville = models.CharField(max_length=100)
    chef_antenne = models.CharField(max_length=110, unique=True)

    def __str__(self):
        return self.nom

class Service(models.Model):
    nom = models.CharField(max_length=100, unique=True)
    chef = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    antenne = models.ForeignKey(Antenne, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nom} - {self.antenne.nom}"


class Employe(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    fonction = models.CharField(max_length=150)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    telephone = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return f"{self.prenom} {self.nom}"


class Equipement(models.Model):
    TYPE_CHOICES = [
        ('ordinateur', 'Ordinateur'),
        ('imprimante', 'Imprimante'),
        ('serveur', 'Serveur'),
        ('autre', 'Autre'),
    ]
    
    statut_choices = [
        ('actif', 'Actif'),
        ('en_reparation', 'En réparation'),
        ('hors_service', 'Hors service'),
        ('reserve', 'Réservé'),
    ]

    nom = models.CharField(max_length=100)
    marque = models.CharField(max_length=50)
    serie = models.CharField(max_length=15, unique=True)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    statut = models.CharField(max_length=50, choices=statut_choices, default='actif')
    utilisateur = models.ForeignKey(Employe, on_delete=models.SET_NULL, null=True, blank=True)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True)
    antenne = models.ForeignKey(Antenne, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.nom} ({self.type})"


class Historique(models.Model):
    ACTION_CHOICES = [
        ('ATTRIBUTION', 'Attribution'),
        ('RETOUR', 'Retour'),
        ('MAINTENANCE', 'Maintenance'),
        ('REPARATION', 'Réparation'),
        ('SUPPRESSION', 'Suppression'),
    ]

    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)
    equipement = models.ForeignKey(Equipement, on_delete=models.CASCADE)
    action = models.CharField(max_length=20, choices=ACTION_CHOICES)
    date_action = models.DateTimeField(auto_now_add=True, db_index=True)
    description = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.action} sur {self.equipement.nom} par {self.employe.nom} le {self.date_action.strftime('%Y-%m-%d %H:%M:%S')}"

gestion_parc/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Employe, Service, Equipement, Historique, Antenne
from django.http import HttpResponse
from .forms import EquipementForm, EmployeForm, ServiceForm, AntenneForm, HistoriqueForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse



@login_required
def ajouter_historique(request):
    if request.method == 'POST':
        form = HistoriqueForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('historique_list')
    else:
        form = HistoriqueForm()
    
    return render(request, 'gestion_parc/ajouter_historique.html', {'form': form})



@login_required
def home(request):
    
    nombre_employe = Employe.objects.all().count()
    nombre_equipements = Equipement.objects.all().count()
    nombre_antennes = Antenne.objects.all().count()
    historique_recent = Historique.objects.all().order_by('date_action').count()
    
    
    return render(request, 'gestion_parc/dashboard.html', locals())


# Liste des employés
@login_required
def liste_employes(request):
    employes = Employe.objects.all()
    paginator = Paginator(employes, 1)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'gestion_parc/liste_employes.html', {'employes': employes, "page_obj": page_obj})

# Détail d'un employé
@login_required
def detail_employe(request, id):
    employe = get_object_or_404(Employe, pk=id)
    return render(request, 'gestion_parc/detail_employe.html', {'employe': employe})

# Liste des services
@login_required
def liste_services(request):
    services = Service.objects.all()
    return render(request, 'gestion_parc/liste_services.html', {'services': services})

# Détail d'un service
@login_required
def detail_service(request, id):
    service = get_object_or_404(Service, pk=id)
    employe_service = Employe.objects.filter(service=id)
    return render(request, 'gestion_parc/detail_service.html', {'service': service, 'employes': employe_service})

# Liste des équipements
@login_required
def liste_equipements(request):
    equipements = Equipement.objects.all()
    paginator = Paginator(equipements, 1)  # Show 25 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, 'gestion_parc/liste_equipements.html', {'equipements': equipements, "page_obj": page_obj})

# Détail d'un équipement
@login_required
def detail_equipement(request, id):
    equipement = get_object_or_404(Equipement, pk=id)
    historique = Historique.objects.filter(equipement=equipement)
    return render(request, 'gestion_parc/detail_equipement.html', {'equipement': equipement, 'historique': historique})


@login_required
def historique_list(request):
    historiques = Historique.objects.all().order_by('-date_action')

    # Récupérer les filtres depuis la requête GET
    employe_id = request.GET.get('employe')
    equipement_id = request.GET.get('equipement')
    action = request.GET.get('action')

    if employe_id:
        historiques = historiques.filter(employe__id=employe_id)
    if equipement_id:
        historiques = historiques.filter(equipement__id=equipement_id)
    if action:
        historiques = historiques.filter(action=action)

    # Pagination : 10 résultats par page
    paginator = Paginator(historiques, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'gestion_parc/historique_list.html', {'page_obj': page_obj})


# Ajouter un employé
@login_required
def ajouter_employe(request):
    if request.method == 'POST':
        form = EmployeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('liste_employes')
    else:
        form = EmployeForm()
    
    return render(request, 'gestion_parc/ajouter_employes.html', {'form': form})

# Ajouter un équipement
@login_required
def ajouter_equipement(request):
    if request.method == "POST":
        form = EquipementForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('liste_equipements')

    else:
        form = EquipementForm()
        
    return render(request, 'gestion_parc/ajouter_equipement.html', {"form": form})







@login_required
def ajouter_service(request):
    if request.method == "POST":
        form = ServiceForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('liste_services')

    else:
        form = ServiceForm()
        
    return render(request, 'gestion_parc/ajouter_service.html', {"form": form})






# modification views
@login_required
def modifier_equipement(request, id):
    equipement = get_object_or_404(Equipement, pk=id)
    if request.method == 'POST':
        form = EquipementForm(request.POST, instance=equipement)
        if form.is_valid():
            form.save()
            messages.success(request, "L'equipement à été modifié avec succès")
            return redirect('liste_equipements')  # Remplacez 'equipement_liste' par votre vue de liste d'équipements
    else:
        form = EquipementForm(instance=equipement)
          
    return render(request, 'gestion_parc/modifier_equipement.html', {'form': form})



@login_required
def modifier_employe(request, id):
    employe = get_object_or_404(Employe, pk=id)
    if request.method == 'POST':
        form = EmployeForm(request.POST, instance=employe)
        if form.is_valid():
            form.save()
            messages.success(request, "L'employé à été modifié avec succès")
            return redirect('liste_employes')
    else:
        form = EmployeForm(instance=employe)
    
    return render(request, 'gestion_parc/modifier_employe.html', {'form': form})


@login_required
def modifier_service(request, id):
    service = get_object_or_404(Service, pk=id)
    if request.method == 'POST':
        form = ServiceForm(request.POST, instance=service)
        if form.is_valid():
            form.save()
            messages.success(request, "Le service à été modifié avec succès")
            return redirect('liste_services')
    else:
        form = ServiceForm(instance=service)
    
    return render(request, 'gestion_parc/modifier_service.html', {'form': form})



# suppression views

@login_required
def supprimer_equipement(request, id):
    equipement = get_object_or_404(Equipement, pk=id)
    
    if request.method == "POST":
        equipement.delete()
        messages.success(request, "Équipement supprimé avec succès !")
        return redirect('liste_equipements')

    return render(request, 'gestion_parc/supprimer_equipement.html', {'equipement': equipement})



@login_required
def supprimer_employe(request, id):
    employe = get_object_or_404(Employe, pk=id)
    
    if request.method == "POST":
        employe.delete()
        messages.success(request, "Employé supprimé avec succès !")
        return redirect('liste_employes')

    return render(request, 'gestion_parc/supprimer_employe.html', {'employe': employe})


@login_required
def supprimer_service(request, id):
    service = get_object_or_404(Service, pk=id)
    if request.method == "POST":
        service.delete()
        messages.success(request, "Service supprimé avec succès !")
        return redirect('liste_services')

    return render(request, 'gestion_parc/supprimer_service.html', {'service': service})




# antenne
# Liste des équipements
@login_required
def liste_antennes(request):
    antennes = Antenne.objects.all()
    return render(request, 'gestion_parc/liste_antennes.html', {'antennes': antennes})




# Détail d'un équipement
@login_required
def detail_antenne(request, id):
    antenne = get_object_or_404(Antenne, pk=id)
    services = Service.objects.filter(pk=id)
    return render(request, 'gestion_parc/detail_antenne.html', {'antenne': antenne, 'services': services})

@login_required
def supprimer_antenne(request, id):
    antenne = get_object_or_404(Antenne, pk=id)
    if request.method == "POST":
        antenne.delete()
        messages.success(request, "antenne supprimé avec succès !")
        return redirect('liste_antennes')

    return render(request, 'gestion_parc/supprimer_antenne.html', {'antenne': antenne})

@login_required
def modifier_antenne(request, id):
    antenne = get_object_or_404(Antenne, pk=id)
    if request.method == 'POST':
        form = AntenneForm(request.POST, instance=antenne)
        if form.is_valid():
            form.save()
            messages.success(request, "L'antenne à été modifié avec succès")
            return redirect('liste_antennes')
    else:
        form = AntenneForm(instance=antenne)
    
    return render(request, 'gestion_parc/modifier_antenne.html', {'form': form})












# authentification

def inscription(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Inscription réussie !")
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/inscription.html', {'form': form})


def connexion(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, "Connexion réussie !")
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/connexion.html', {'form': form})

gestion_parc/templates/gestion_parc/ajouter_employes.html
{% extends "base.html" %}

{% block title %}Page d'ajout d'un employé{% endblock  %}

{% block content %}

    <div class="card">
        <h1>Ajouter employer</h1>

        <form action="" method="post">

            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Ajouter</button>
        </form>
    </div>

{% endblock  %}

gestion_parc/templates/gestion_parc/ajouter_equipement.html
{% extends "base.html" %}

{% block title %}Ajout d'un équipement{% endblock  %}


{% block content %}

    <div class="container mt-5">
        <h2>Ajouter un équipement</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Ajouter</button>
        </form>
    </div>

{% endblock  %}

gestion_parc/templates/gestion_parc/detail.html
{% extends 'base.html' %}

{% block title %}Détails de l'Employé{% endblock %}

{% block content %}
    <h1>Détails de {{ employe.prenom }} {{ employe.nom }}</h1>
    
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item"><strong>Email :</strong> {{ employe.email }}</li>
                <li class="list-group-item"><strong>Téléphone :</strong> {{ employe.telephone }}</li>
                <li class="list-group-item"><strong>Service :</strong> {{ employe.service.nom if employe.service else "N/A" }}</li>
                <li class="list-group-item"><strong>Date d'embauche :</strong> {{ employe.date_embauche }}</li>
            </ul>
        </div>
        <div class="col-md-6">
            <h4>Historique des équipements :</h4>
            <ul class="list-group">
                {% for equipement in employe.equipement_set.all %}
                    <li class="list-group-item">
                        <strong>{{ equipement.nom }}</strong><br>
                        Type : {{ equipement.type_equipement }}<br>
                        État : {{ equipement.etat }}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <!-- Retour à la liste -->
    <a href="{% url 'liste_employes' %}" class="btn btn-secondary mt-4">Retour à la Liste des Employés</a>
{% endblock %}

gestion_parc/templates/gestion_parc/detail_employe.html
{% extends 'base.html' %}

{% block title %}Détails de l'Employé{% endblock %}

{% block content %}
    <h1>Détails de {{ employe.prenom }} {{ employe.nom }}</h1>
    
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item"><strong>Email :</strong> {{ employe.email }}</li>
                <li class="list-group-item"><strong>Téléphone :</strong> {{ employe.telephone }}</li>
                <li class="list-group-item"><strong>Service :</strong> {{ employe.service.nom }}</li>
                <li class="list-group-item"><strong>Fonction :</strong> {{ employe.fonction }}</li>
            </ul>
        </div>
        <div class="col-md-6">
            <h4>Historique des équipements :</h4>
            <ul class="list-group">
                {% for equipement in employe.equipement_set.all %}
                    <li class="list-group-item">
                        <strong>{{ equipement.nom }}</strong><br>
                        Type : {{ equipement.type }}<br>
                        État : {{ equipement.statut }}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <!-- Retour à la liste -->
    <a href="{% url 'liste_employes' %}" class="btn btn-secondary mt-4">Retour à la Liste des Employés</a>
{% endblock %}

gestion_parc/templates/gestion_parc/detail_service.html
{% extends 'base.html' %}

{% block title %}Détails du Service{% endblock %}

{% block content %}
    <h1>Détails de {{ service.nom }}</h1>
    
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item"><strong>Nom :</strong> {{ service.nom }}</li>
                <li class="list-group-item"><strong>Chef du Service :</strong> {{ service.chef }}</li>
                <li class="list-group-item"><strong>Description :</strong> {{ service.description}}</li>
                <li class="list-group-item"><strong>Antenne :</strong> {{ service.antenne }}</li>
            </ul>
        </div>
        <div class="col-md-6">
            <h4>La liste des employés du service :</h4>
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Nom</th>
                        <th>Email</th>
                        <th>Service</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for employe in employes %}
                        <tr>
                            <td>{{ employe.nom }} {{ employe.prenom }}</td>
                            <td>{{ employe.email }}</td>
                            <td>{{ employe.service.nom  }}</td>
                            <td>
                                <!-- Détail de l'employé -->
                                <a href="{% url 'detail_employe' employe.id %}" class="btn btn-info btn-sm">Détails</a>
        
                                <!-- Editer l'employé (si vous ajoutez une fonctionnalité de suppression) -->
                                <a href="{% url 'modifier_employe' employe.id %}" class="btn btn-warning btn-sm">Éditer</a>
                                
                                <!-- Supprimer l'employé (si vous ajoutez une fonctionnalité de suppression) -->
                                <a href="{% url 'supprimer_employe' employe.id %}" class="btn btn-danger btn-sm">Supprimer</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Retour à la liste -->
    <a href="{% url 'liste_services' %}" class="btn btn-secondary mt-4">Retour</a>
{% endblock %}

gestion_parc/templates/gestion_parc/liste_employes.html
{% extends 'base.html' %}

{% block title %}Liste des Employés{% endblock %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert 
                {% if message.tags == 'success' %}alert-success
                {% elif message.tags == 'info' %}alert-info
                {% elif message.tags == 'warning' %}alert-warning
                {% elif message.tags == 'error' %}alert-danger
                {% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}


    <h1 class="mb-4">Liste des Employés</h1>
    
    <!-- Ajout d'un nouvel employé -->
    <a href="{% url 'ajouter_employe' %}" class="btn btn-primary mb-3">Ajouter un Employé</a>

    <!-- Tableau des employés -->
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Nom</th>
                <th>Email</th>
                <th>Service</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for employe in page_obj %}
                <tr>
                    <td>{{ employe.nom }} {{ employe.prenom }}</td>
                    <td>{{ employe.email }}</td>
                    <td>{{ employe.service.nom  }}</td>
                    <td>
                        <!-- Détail de l'employé -->
                        <a href="{% url 'detail_employe' employe.id %}" class="btn btn-info btn-sm">Détails</a>

                        <!-- Editer l'employé (si vous ajoutez une fonctionnalité de suppression) -->
                        <a href="{% url 'modifier_employe' employe.id %}" class="btn btn-warning btn-sm">Éditer</a>
                        
                        <!-- Supprimer l'employé (si vous ajoutez une fonctionnalité de suppression) -->
                        <a href="{% url 'supprimer_employe' employe.id %}" class="btn btn-danger btn-sm">Supprimer</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

<!-- PAGINATION AVEC NUMÉROTATION -->
<nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">&laquo; Première</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Précédent</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Suivant</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Dernière &raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

gestion_parc/templates/gestion_parc/liste_equipements.html
{% extends 'base.html' %}

{% block title %}Liste des Equipements{% endblock %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert 
                {% if message.tags == 'success' %}alert-success
                {% elif message.tags == 'info' %}alert-info
                {% elif message.tags == 'warning' %}alert-warning
                {% elif message.tags == 'error' %}alert-danger
                {% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    <h1 class="mb-4">Liste des Equipements</h1>
    
    <!-- Ajout d'un nouvel employé -->
    <a href="{% url "ajouter_equipement" %}" class="btn btn-primary mb-3">Ajouter un Equipements</a>

    <!-- Tableau des employés -->
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Nom</th>
                <th>Série</th>
                <th>Type</th>
                <th>Statut</th>
                <th>Utilisateur</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for equipement in page_obj %}
                <tr>
                    <td>{{ equipement.nom }}</td>
                    <td>{{ equipement.serie }}</td>
                    <td>{{ equipement.type  }}</td>
                    <td>{{ equipement.statut }}</td>
                    <td>{{ equipement.utilisateur.nom  }}</td>
                    <td>
                        <a href="{% url "detail_equipement" equipement.id %}" class="btn btn-info btn-sm">Détails</a>
                        <a href="{% url 'modifier_equipement' equipement.id %}" class="btn btn-warning btn-sm">Éditer</a>
                        <a href="{% url 'supprimer_equipement' equipement.id %}" class="btn btn-danger btn-sm">Supprimer</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- PAGINATION AVEC NUMÉROTATION -->
<nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">&laquo; Première</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Précédent</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Suivant</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Dernière &raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

gestion_parc/templates/gestion_parc/listing.html
{% extends 'base.html' %}

{% block title %}Liste des Employés{% endblock %}

{% block content %}
    <h1 class="mb-4">Liste des Employés</h1>
    
    <!-- Ajout d'un nouvel employé -->
    <a href="{% url 'ajouter_employe' %}" class="btn btn-primary mb-3">Ajouter un Employé</a>

    <!-- Tableau des employés -->
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Nom</th>
                <th>Email</th>
                <th>Téléphone</th>
                <th>Service</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for employe in employes %}
                <tr>
                    <td>{{ employe.nom }} {{ employe.prenom }}</td>
                    <td>{{ employe.email }}</td>
                    <td>{{ employe.telephone }}</td>
                    <td>{{ employe.service.nom if employe.service else "N/A" }}</td>
                    <td>
                        <!-- Détail de l'employé -->
                        <a href="{% url 'detail_employe' employe.id %}" class="btn btn-info btn-sm">Détails</a>
                        
                        <!-- Supprimer l'employé (si vous ajoutez une fonctionnalité de suppression) -->
                        <a href="#" class="btn btn-danger btn-sm">Supprimer</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

gestion_parc/templates/gestion_parc/modifier_antenne.html
{% extends "base.html" %}

{% block title %}Modification de l'antenne{% endblock  %}


{% block content %}

    <div class="container mt-5">
        <h2>Modifier l'antenne</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Mettre à jour</button>
        </form>
    </div>

{% endblock  %}

gestion_parc/templates/gestion_parc/modifier_equipement.html
{% extends "base.html" %}

{% block title %}Modification d'un équipement{% endblock  %}


{% block content %}

    <div class="container mt-5">
        <h2>Modifier un équipement</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Mettre à jour</button>
        </form>
    </div>

{% endblock  %}